### ISSUE TITLE
How to compile SHOGUN with MATLAB interface?

### ISSUE THREAD

**Issue by research2010** [shogun-toolbox/shogun#2017]
I have download the source code of version 0.7.3 in the official website. And the configure script is as follows:

```
    ./configure --prefix=`pwd`/../ --interfaces=libshogun,libshogunui,matlab,python,cmdline
```

The compiling procedure is success. But, there is no `sg.mexa64` file. Does anyone give me some advice,please? Thanks.

**Comment by luckybuilding** [comment]
Hi, I have found this now and wanted to use it. Is this still available on shogun?! I don't see the link!

**Comment by iglesias** [comment]
Hey @luckybuilding, what link are you referring to?

Anyway, if you would like to use Shogun in Matlab, you definitely can using Shogun 5.0.0 or earlier. I just tried it myself with Shogun 4.0.0 and Matlab R2016b.

**Comment by luckybuilding** [comment]
Hey @iglesias ,
Thanks for your reply. I was referring to the top link (https://github.com/shogun-toolbox/shogun/blob/develop/doc/md/INSTALL.md#matlab)

I think the support for MATLAB has been removed on Shogun 5.0.0.
I don't see anything about Matlab on the latest versions!

Can you provide a instruction for compile and use of it on MATLAB?

**Comment by iglesias** [comment]
You don't see anything about Matlab on the latest versions because as mentioned above you have to use Shogun 4.0.0 or earlier to use Shogun in Matlab.

In a nutshell, the main instruction for compilation is to configure the build with the cmake option `MatlabStatic` set to `ON`. Now depending on the version of Matlab you are using, such as if you are using a version more modern than Shogun 4.0.0, you may need to do a couple of other updates in the build files.

If you need help with this, I could help you interactively via irc in our channel.

**Comment by luckybuilding** [comment]
Thanks. Isn't it going to be supported in next versions?
Because, I'm starting a line of coding for a project that would need to be
updated later and I don't wanna get stuck in an late unsupported version.

On Nov 21, 2017 11:49 AM, "Fernando J. Iglesias García" <
notifications@github.com> wrote:

You don't see anything about Matlab on the latest versions because as
mentioned above you have to use Shogun 4.0.0 or earlier to use Shogun in
Matlab.

In a nutshell, the main instruction for compilation is to configure the
build with the cmake option MatlabStatic set to ON. Now depending on the
version of Matlab you are using, such as if you are using a version more
modern than Shogun 4.0.0, you may need to do a couple of other updates in
the build files.

If you need help with this, I could help you interactively via irc in our
channel.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/shogun-toolbox/shogun/issues/2017#issuecomment-345949956>,
or mute the thread

**Comment by iglesias** [comment]
This will depend mainly on whether Matlab becomes supported by Swig.

**Comment by karlnapf** [comment]
SWIG and matlab do work together, there is a number of project who are
doing it. Check the issues if you want to help us re-enabling this feature.
Mainly requires someone to dive into it. Interested?

2017-11-21 12:41 GMT+00:00 Fernando J. Iglesias García <
notifications@github.com>:
