### ISSUE TITLE
Native implementations in Linalg.

### ISSUE THREAD

**Issue by sanuj** [shogun-toolbox/shogun#2667]
@karlnapf @lambday I would like to work on this. Currently `HAVE_LINALG_LIB` is defined provided `eigen3` & `viennacl` are found, and supported c++11 compiler is used. We can change it to defining `HAVE_LINALG_LIB` only when the supported c++11 compiler is used. This can be achieved by altering `shogun/CMakeLists.txt` alone.

We can give runtime errors for the operations that can't be implemented natively in linalg. Please list down the operations that can be implemented natively (i guess Vector/Matrix dot and sum are one of them).

**Comment by sanuj** [comment]
Nice to hear from you @lambday :D. I think not disturbing `HAVE_LINALG_LIB` is a good idea. Looking forward to your modifications.

**Comment by lambday** [comment]
@sanuj check PR #2672. I have just added dot to check if the NATIVE backend thing is working. Once this change is merged, you can start working on native implementations for other operations in similar fashion. 

Please make sure that everything compiles even in absence of eigen3/viennacl. Unit-tests for NATIVE should work even when we don't have any external libs.

Another cleanup work would be to use this `linalg::dot(a, b)` instead of the existing dot methods (replace everywhere `dot` operation is used _without specifying any backend_ since it is safe now).

**Comment by sanuj** [comment]
@lambday Great! The PR looks good :) I'll start the clean up work and add more native implementations in a similar fashion as soon as the PR is merged. Loads of functions can be cleaned up and more can be implemented natively (list is in the mailing list, Should I add it here just so we have a record?).

**Comment by lambday** [comment]
@sanuj cool. So the key to add native implementation to linalg is that we'll keep those operations (in modules) outside of the `HAVE_LINALG_LIB` guard. No other special tricks required. Please keep in mind that we don't intend to provide native implementation for _everything_ . Just the basic trivial things (most of them were already there in SGVector and SGMatrix). Before you push, you _must_ check locally (compile and run the unit-tests)
- with all the backends configured 
- without the backends configured
(I do a silly thing - I just temporarily rename the include dirs of eigen3 and viennacl to something else so that cmake can't find them. Maybe there is a better way to turn this off just by cmake.)

Don't worry about adding the list here. We have the mailing list archived already :)
Wait for this PR to be merged first :) Once I hear green from @iglesias I will merge it.

**Comment by lambday** [comment]
Oh and please use viennacl 1.5.x and not 1.6. I noticed some compatibility issues with that locally. I'll have to address that later after the release. You need to install opencl as well.

**Comment by sanuj** [comment]
Got it :+1:

**Comment by sanuj** [comment]
@lambday @iglesias 
I'm not sure if `CMath::dot` can be replaced by `linalg::dot<linalg::Backend::NATIVE>` everywhere in shogun since it needs to be surrounded by `if defined(HAVE_CXX0X) || defined(HAVE_CXX11)`. So when `HAVE_CXX0X` or `HAVE_CX11` are not defined then the compiler will throw errors. I was thinking of removing `CMath::dot` entirely but now I'm not sure whether it will work on not. What do you think?

**Comment by iglesias** [comment]
I think that's actually a very good point, @sanuj.

@lambday, is it possible to refactor linalg so that C++11 is an optional dependency so we can have parts of it (e.g. dot product) that do not depend on it?

**Comment by lambday** [comment]
@iglesias I guess at present the only c++11 thing that is there in linalg is the enum class thing (rest, variadic templates etc are now removed). I'll see if we really need enum class or just enum will do. hard to test locally since I don't have a compiler that doesn't support c++11 :P 

@sanuj well, the idea is to use just `linalg::dot(...);` instead (without specifying any backend). What's the use of having eigen3/viennacl powered dots if we plan to use native always! :D let dot use default which anyways falls back to native if 3rd party libraries are not found! makes sense?

**Comment by lambday** [comment]
@iglesias why aren't we using a compiler in travis that supports c++11? that's not in our hand? gcc supports c++11 from 4.6.x itself (IIRC). IMO if people still use a compiler that doesn't support c++11 they should be punished :D

**Comment by sanuj** [comment]
@lambday Yes indeed. But if we use `linalg::dot(...)` then also we would need to surround the code by `if defined(HAVE_CXX0X) || defined(HAVE_CXX11)`. So I guess for now we shall use `CMath::dot` till c++11 dependency is resolved.

**Comment by lambday** [comment]
@sanuj ya I got that. I think just replacing the enum class thing with enum we should be fine (all `linalg::Backend::EIGEN3` [and so...] would also have to be changed by just `EIGEN3` [and so...] as well since enum doesn't have their own scope). if that works then we don't need c++11 for linalg.

**Comment by iglesias** [comment]
Yeah, I agree, @lambday. For me it would be fine to make C++11 a compulsory dependency. But I guess there might be some cons with that? @karlnapf @vigsterkr @lisitsyn @sonney2k

**Comment by karlnapf** [comment]
Fine from my side, we should take advantage of all the modern stuff in the language these days anyways.
I much rather prefer a modern code over being compatible to ancient computer systems.

**Comment by iglesias** [comment]
And also, it is just a matter of saying, Shogun v. x.x.x onwards requires a gcc v. > y.y.y., otherwise use an older version of Shogun. It is not like Shogun would not be usable at all in old systems.

**Comment by lisitsyn** [comment]
I believe that as long as we are source-based not distribution-based modern compiler is ok.

**Comment by karlnapf** [comment]
So is there any conclusion here?
Make c++11 mandatory?

**Comment by karlnapf** [comment]
We will wait (at least a bit) with c++11 (see discussion on mailing list)
As eigen3 is now always enabled, we dont need the native implementations anymore
