### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ghalghaz** [shogun-toolbox/shogun#2681]
Hi,

I tried the example in https://github.com/shogun-toolbox/shogun/wiki/QUICKSTART.

I got the following error:

~/shogun-install/share/shogun/examples/libshogun$ sudo chmod +x ./so_multiclass_BMRM && ./so_multiclass_BMRM
Segmentation fault (core dumped)

environment;
shogun 3.2 
data 0.8
ubuntu 14.04

thanks for helping

**Comment by iglesias** [comment]
Hello, @ghalghaz. I just trieda fresh install with current develop (Shogun 3.2.2) in Ubuntu 14.04 and the example worked fine.

What exact version is the one you are using and what line did you use for cmake exactly?

Small remark: I didn't need to do `sudo chmod +x ./so_multiclass_BMRM` since the file had already executable permissions on. Also, I didn't need to export the LD_LIBRARY_PATH as indicated in the QUICKSTART.

**Comment by ghalghaz** [comment]
I use shogun 3.2.0 and use 
cmake -DCMAKE_INSTALL_PREFIX="$HOME/shogun-install" ..
I followed all command in https://github.com/shogun-toolbox/shogun/wiki/QUICKSTART. 
You are using shogun 3.2.2, where I can download it?..
in http://shogun-toolbox.org/page/home/ the newest version is still shogun 3.2.0

**Comment by iglesias** [comment]
I tried with the current develop branch of the repository. You can get that locally using git.

I am currently trying with the version you mentioned.

**Comment by iglesias** [comment]
@ghalghaz, I just tried with version 3.2.0 and the example worked fine as well. I did also a run with valgrind and it didn't detect anything abnormal.

Could you run the program with gdb and provide more information about the crash? Note that in order to get more information from gdb you may need to compile Shogun in debug mode rather than release (which is the default). You can do that by configuring with the following line:

`cmake -DCMAKE_BUILD_TYPE=Debug ..`,

you can also use the other options you were using before, i.e.,

`cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="$HOME/shogun-install"` ..

**Comment by ghalghaz** [comment]
@iglesias 
Here the message:

(gdb) b 1
Note: breakpoint 1 also set at pc 0x401eda.
Breakpoint 2 at 0x401eda: file /home/xxx/shogun-3.2.0/examples/undocumented/libshogun/so_multiclass_BMRM.cpp, line 1.
(gdb) run
Starting program: /home/xxx/shogun-install/share/shogun/examples/libshogun/so_multiclass_BMRM 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffef492700 (LWP 18546)]

Program received signal SIGSEGV, Segmentation fault.
_IO_vfprintf_internal (s=0x0, format=0x40331c "%d", ap=ap@entry=0x7fffffffd708)
    at vfprintf.c:1295
1295	vfprintf.c: No such file or directory.

**Comment by iglesias** [comment]
Could you also please provide the information given by backtrace (bt). Also, since the logs are starting to get somewhat long, please use either gist or pastebin.

Out of curiosity, why are you setting those two breakpoints?
