### ISSUE TITLE
a bug in linalg

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2801]
@lambday @karlnapf 
the following code can reproduce the bug 

```
#include <shogun/mathematics/linalg/linalg.h>
void debug()
{
SGVector<float64_t> left(2);
left[0]=8.57765;
left[1]=4.57765;
SGMatrix<float64_t> left_mat(left.vector,1,left.vlen,false);
SGMatrix<float64_t> right_mat(left.vector,left.vlen,1,false);
SGMatrix<float64_t> res(1,1);
linalg::matrix_product(left_mat,right_mat,res);
}
```

when  `cmake -DENABLE_EIGEN=OFF -DENABLE_VIENNACL=ON`, res is `0.0`

when `cmake -DENABLE_EIGEN=ON -DENABLE_VIENNACL=OFF`, res is `94.53095904500000301596`

**Comment by lambday** [comment]
@yorkerlin @karlnapf hey man this seems really weird. I can reproduce this locally. The funny part is, if I replace SG with CGPU counterparts, things work perfectly fine. So, I thought that it must be the constructor `CGPUMatrix<T>::CGPUMatrix(const SGMatrix<T>& cpu_mat)` that gets called when we pass those SGMatrices to matrix_product. I put some debug texts there and I get this
```
[DEBUG] Constructing a GPU matrix from a CPU matrix!
GPU matrix=[
[	0]
]
[DEBUG] Constructing a GPU matrix from a CPU matrix!
GPU matrix=[
[	8.57765000000000022],
[	4.57765000000000022]
]
[DEBUG] Constructing a GPU matrix from a CPU matrix!
GPU matrix=[
[	8.57765000000000022,	4.57765000000000022]
]
matrix=[
[	0]
]
```
(params parsed right to left). So things do seem fine up to this point - don't know what part is messing it up. Gotta dig deeper for this.

**Comment by lambday** [comment]
Oh I see! It stores the result into a temporarily created GPU matrix. So res (which is SGMatrix) is still empty. We need to provide a version that returns the result matrix.

**Comment by lambday** [comment]
@yorkerlin back then we added the result parameter in those methods because CPU < --- > GPU data transfer is costly. But we do need the standard versions that would simply return the result. Whenever using a linalg method with global backend (i.e. not specifying any backend), we should use those only. Will ping you when I add that method. Thanks for pointing out this bug! :)

**Comment by karlnapf** [comment]
Great interaction guys, well spotted @yorkerlin !
Pleasure to read along this discussion!

**Comment by lambday** [comment]
@yorkerlin @karlnapf I will add similar things for other linalg methods. I've got an idea though. I remember discussing something regarding this with Khaled. The key point is, even though this approach makes things work, **but** the back and forth CPU-GPU data transfer really kills the performance. You see what we're doing here is, we're copying two CPU matrices to the GPU, compute the result and storing it temporarily in the GPU memory and then again transferring it back to CPU SGMatrix. Imagine doing that over and over (maybe inside a loop) for some ~1000x1000 matrices.

So I was thinking how about we have some cmake switch to make all matrices and vectors GPU ones **shogun-wise** ? So as devs we'll simply forget about this SG/CGPU matrices/vectors - we'll write same code but that cmake switch will decide which memory it should use. That we we won't be compromising with the performance that we can milk from GPU.

**Comment by karlnapf** [comment]
So the idea is that everything happens in GPU memory?

**Comment by karlnapf** [comment]
If that works, I love the idea!
I am a bit sceptical whether it is possible to actually do this? Thinking about all the different backends used....i.e. @yorkerlin heavily uses eigen3, but then also some linalg calls....
Maybe we need to give this decision to the programmer? They know best when transfers should be done? And there should be a debug switch which counts the number of such transfers in order to profile shogun

**Comment by lambday** [comment]
I agree that this decision should be left to the programmer - choose a particular matrix type and a particular backend if you want anything specific. I was thinking from the use-case that @yorkerlin is doing here. Without any backend specified, these operations will make the CPU-GPU transfer for every linalg call when ViennaCL is global backend.

The way I was thinking of achieving this is to make SGMatrix inherit from either of a CPU/GPU matrix based on a preprocessor flag that will be set using cmake. So same SGMatrix will work for both the envs - same interface just the internals changed. But yes when eigen3 calls are used so frequently, then I'm not sure if this plan do any good. I don't know if Eigen::Map thing works with GPU/ViennaCL memory array. Maybe it is worth looking at! :) 

Profiling is totally possible though.

**Comment by yorkerlin** [comment]
@karlnapf @lambday 
Let's `first` test the `linalg` using the FITC inference.

In my opinion, at least for GP modules  without any backend specified, eigen3 should be the default `backend` unless eigen3 is not available.

For kernel modules (eg, GaussianARD kernel), ideally, we may want the following things 
* developers use `global` linalg methods without any backend specified
* users pass a parameter `flag` to the global methods so that users can decide whether GPU is used or not in `running time`. (assuming  ViennaCL and eigen3 are available). 
* if any one of the libs (ViennaCL and eigen3) is missing, ignore the `flag` when the global methods are called.

**Comment by lambday** [comment]
@yorkerlin 

- Default is eigen3 for everything. So no problem there
- The flag thing is possible. However, we'll be having to copy the data, CPU to/from GPU. See, the flag you mentioned can very well determine which backend is used for the operations, even at runtime (one can easily write if-else/switch with those with specified backend). But for properly using GPU, one better rely on using a CGPUMatrix instead of SGMatrix. We can however choose to use SGMatrix everywhere - but that is where all the copying will take place *if* the flag specifies ViennaCL. I'm not very sure how bad that would be. Maybe a benchmark would help. I'll do that :) 

Sorry my comments aren't really your algorithm specific but more generic (more from linalg point of view). I should really spend some time knowing the stuffs :(

**Comment by yorkerlin** [comment]
@lambday 
Maybe we can do some benchmarks to determine when GPU should be used.
For example, y-axis is the speedup when GPU is used and x-axis is  the size of of matrix (assuming the matrix is `square` first) n for the following cases:
* matrix-by-matrix product
* matrix-by-vector product
* matrix-inverse
* matrix decompositions (LU, QR, Chol and others)
* others operations

**Comment by lambday** [comment]
@yorkerlin sounds like a great idea! Not sure about matrix-inverse though. Never used that :D Heiko?

Okay I'll do these benchmarks. Buying one day time.

**Comment by yorkerlin** [comment]
@lambday 
see the updated comments.
Looking forward to your benchmarks :) !

**Comment by karlnapf** [comment]
These benchmarks are super useful. Please document carefully so they are more or less reproducible.
MatrixInverse is forbidden in Shogun. I only allow QR, Cholesky, SVD and their brothers and sisters ;)

I think the "make the programmer decide" approach might be best.
About doing everything on the GPU memory. If the eigen maps still work on GPU memory, then we should do this. I think in fact that it is an awesome idea then. But some more thinking required here. Maybe someone else knows about graphic cards. @lisitsyn ?

**Comment by yorkerlin** [comment]
@karlnapf 
matrix-inverse (base on LU?)

**Comment by yorkerlin** [comment]
In the case of matrix-inverse-by-vector product matrix-inverse-by-matrix product, matrix-inverse is forbidden.

If we need to compute the matrix-inverse alone, we may need to use LU? (eg, we use `precision matrix` as a permeameter instead of `covariance` matrix)
