### ISSUE TITLE
Support Sphinx-based examples

### ISSUE THREAD

**Issue by lisitsyn** [shogun-toolbox/shogun#2816]
Inspired by @karlnapf https://github.com/karlnapf/shogun_manual

 * ~~Fix the issue with width of containers~~ 
 * ~~Put all target languages in one place rather than having them hard-coded in multiple files~~
 * ~~Integrate meta-example generation. Rather than having the different listings in the repository explicit. Only the *.sg files should remain~~
 * ~~Clean up directory structure in a scallable way.~~
 * Integrate in CMake process in a feature branch
 * Tune visuals and high-level structure of manual
 * Document the sphinx plugin to allow others to understand/maintain
 * Write README on how to put content

**Comment by lisitsyn** [comment]
@karlnapf current status
![screen shot 2015-04-15 at 19 12 29](https://cloud.githubusercontent.com/assets/424629/7163571/7032e69a-e3a3-11e4-86bc-fbfe906d3263.png)

**Comment by lisitsyn** [comment]
30409a71019c3a5b2247f994ff8208c8804b58fa merged that into feature branch feature/sphinxdoc

**Comment by karlnapf** [comment]
Great!

Some intermediate things that I noticed:
 * the example files should not be named "knn.sg.py" but rather "knn.py"
 * The example code should not be in the sphinx folder, but rather in the global examples folder
 * Parsing and generating the examples should not happen within python sphinx. I would prefer if cmake would generate examples in target languages, and then sphinx just loads the files. Then we also can replace the current set of examples with the meta examples, and dont have two set of them, there will be lots of overlap otherwise. We then also work towards replacing the old API examples when we work on the documentation. Thoughts?

**Comment by karlnapf** [comment]
@sorig check it out and let us know if you have feedback. Might also be nice for your writeup

**Comment by karlnapf** [comment]
All done, just need to merge now
