### ISSUE TITLE
Investigate cereal for serialization

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2999]
http://uscilab.github.io/cereal/

Write a minimal use-case where a Shogun class is serialized using this library

**Comment by Soham0** [comment]
Hi,

I am Soham and I am doing my MS in Computer Science and Engineering from IIIT Hyderabad,India. I am extremely interested in contributing to Shogun ML Toolbox. My interests are in Machine Learning, Optimization and Deep Learning. I am comfortable with Python, Octave, Java and C++.  Is this a good place to start? If not can you suggest where I should start . Any help would be immensely welcome. Kindly guide me in the right direction.

Thanks,
Soham Saha

**Comment by lgoetz** [comment]
Hey Soham, 

Welcome to Shogun! since you're replying to #2999, I suggest you pick your favourite Shogun class and try to serialise it with cereal. If that works, pick another one :) 
You can also attempt any of the other issues labelled as "entrance", for example #3000 or an easy one #2996.

Here's a full [list](https://github.com/shogun-toolbox/shogun/issues?q=is%3Aopen+is%3Aissue+label%3Aentrance).

**Comment by karlnapf** [comment]
Hi @Soham0, welcome!
It is better to introduce yourself (and ask such questions) on the mailing list. We should discuss issue related things here to keep the thread clean.

Apart from that, @lgoetz is absolutely right, try to build a prototype of a Shogun class that is serialised with cereal. This task might be a bit more tricky than others, so only attempt it if you know a bit of c++

**Comment by souravsingh** [comment]
@karlnapf Can I know about the classes that need serialization? I believe SGVector, SGMatrix and SGVector are serialized

**Comment by karlnapf** [comment]
We have something as a result of pan's gsoc2016 project
