### ISSUE TITLE
Add mean computation to linalg

### ISSUE THREAD

**Issue by youssef-emad** [shogun-toolbox/shogun#3051]
The goal is to extend [linalg](http://shogun-toolbox.org/doc/en/latest/dir_0d103e974bf2461595574c32f82fb9be.html) to have mean computation operations.

**Comment by karlnapf** [comment]
Can collect patches that need this here:

#3044

**Comment by Ahmkel** [comment]
I am interested in this.
Could you please explain what's needed in more details?

**Comment by karlnapf** [comment]
Check the linalg readme and read the code and unit tests. Then try to add the operation. There is already a lot of summing in the redux module so this is a very simple task

**Comment by OXPHOS** [comment]
Hi, 
I had a look at the code. Since linalg does all the matrix computation, I guess I need to implement a Mean module independent of all current modules in linalg.h, and calculate the mean.row and mean.col of matrices? Did I take this too easy?
I had no experience in coding large projects and I really would like to learn! Thanks!

**Comment by karlnapf** [comment]
There already is a sum redux module. But yes

**Comment by theaverageguy** [comment]
Is this one done @karlnapf ? Can be closed I guess.
