### ISSUE TITLE
use eigen3 in kernel ridge regression

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3095]
1. Use eigen3 to solve the linear system. Put this into a seperate method `solve_krr_system` (to be overloaded in approximate KRR classes like #3508 #3057 #3024 )
2. Remove the Iterative Gauss Seidel method
3. Optional Add a subclass of KRR, which solves the linear system using Gauss seidel and early stopping. However, the iterative linear solver should not be part of this class,  but part of linalg. Conjugate gradient is also an option (and already implemented)

Step 1 will affect the integration test for the [meta examples](https://github.com/shogun-toolbox/shogun/tree/develop/doc/cookbook), which has to be updated accordingly.

**Comment by karlnapf** [comment]
I think this will also fix the [buildbot error](http://buildbot.shogun-toolbox.org/builders/deb1%20-%20libshogun) on kernel ridge regression

**Comment by sanuj** [comment]
@karlnapf I'm almost done with this. I wanted to discuss some points before I send a PR:
* All viennacl calls are in pseudo inverse method. Do we want to keep the pseudo inverse method, if yes then how can i replace the viennacl calls?
* Will there be any case when the kernel matrix is not a square matrix? For LLT, I have assumed that kernel matrix will always be a square matrix.

LLT in KRR is working, I have tested it. The integration test fail due to some slight changes in decimals of alpha so I need to update the data file. Also, there are no unit test for KRR (shall i add one?).

**Comment by karlnapf** [comment]
* no need to do viennacl calls, just use eigen3 itself (if you add a LLT solve to linalg, please send a seperate PR, and then send another PR for using this linalg llt solve in KRR)
 * for KRR training, the kernel matrix is always square symmetric psd
 * Unit tests are very important, make sure to test a few corner cases
