### ISSUE TITLE
Create nightly binary packages for Fedora

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3131]
This is an (easy) entrance task for the installation project: Create a Python script that creates a binary package of the latest Shogun on Fedora linux. We want to include this in our buildbot.

@besser82 @vigsterkr can answer questions

**Comment by arianepaola** [comment]
Here is a snippet from my working buildbot setup @karlnapf. It is building shogun 4.1.0 at the moment. It would be possible to create nightly rpms by specifying the tarball URL for the develop branch below.

```
fedoraRPMFactory = util.BuildFactory()

fedoraRPMFactory.addStep(steps.Git(repourl='git://pkgs.fedoraproject.org/rpms/shogun.git', branch='master', mode='incremental', submodules=True, progress=True, retryFetch=True))
fedoraRPMFactory.addStep(steps.ShellCommand(command=['wget', '-c', 'ftp://shogun-toolbox.org/shogun/releases/4.1/sources/shogun-4.1.0.tar.bz2']))
fedoraRPMFactory.addStep(steps.ShellCommand(command=['wget', '-c', 'http://pkgs.fedoraproject.org/repo/pkgs/gmock/gmock-1.7.0.zip/073b984d8798ea1594f5e44d85b20d66/gmock-1.7.0.zip']))
fedoraRPMFactory.addStep(steps.RpmBuild(specfile="shogun.spec", dist='.f23'))

c['builders'] = []
c['builders'].append(
    util.BuilderConfig(name="shogun-fedora-23_gcc-5_rpmbuild",
      workernames=["shogun-fedora-23"],
      factory=fedoraRPMFactory))

```

@besser82 @vigsterkr Is it possible to trigger a source download using rpmbuild instead of using the source archive specified in sources? I am getting a version mismatch, when I try to work with archives like the one below.

My setup can also download files according to https://fedoraproject.org/wiki/Packaging:SourceURL?rd=Packaging/SourceURL from GitHub.

An example URL is:
https://github.com/shogun-toolbox/shogun/archive/9a75c9509cc5188ce522f4b6e79f3ee9257f8f3b/shogun-git-9a75c95.tar.gz

Thanks, Ariane

**Comment by karlnapf** [comment]
@arianepaola and another one for you :)

**Comment by arianepaola** [comment]
@karlnapf sure :-)

**Comment by karlnapf** [comment]
@besser82 we have new updated nightly binaries now, any way we can include fedora in there?
@vigsterkr

**Comment by vigsterkr** [comment]
no need
