### ISSUE TITLE
Add type cast for SGVector 

### ISSUE THREAD

**Issue by OXPHOS** [shogun-toolbox/shogun#3164]
I am thinking about enabling cast of SGVector<int> to SGVecotr<float>. As I'll be moving things around, I want to make the idea solid before I start.

I'll add method to `linalg.internal.implementation.util`(?) as `TypeConverter`.

I want to move the variable cast method currently in `MeanEigen3` to `TypeConverter`, i.e.:

```
template <typename inputType>
struct int2float
{
	using floatType = inputType;
};
```

Also, to calculate rowwise and columnwise mean, we need convert `int` vector to `float` vector. I'll add a convert method in `TypeConverter`, by going through every element in vector, casting the element to float type, and returning float type vector.

Please let me know if there's anything I can add/improve.

**Comment by lambday** [comment]
Hi @OXPHOS 

Maybe copying an entire vector/matrix is not the way to go for computing means. Imagine we call `mean()` a billion times, we create a billion temporary copies, which are of no use when the method is done. I'd rather compromise the float-int thingi for the sake of performance.

I think the way to go for is like this:

- For Eigen3 backend, don't bother about return-type. Just return whatever the corresponding eigen method returns. We don't need to compute sum and divide by len then. We can just call `mean()`, or `rowwise().mean()`, `colwise().mean()` or so.. The return type in the latter two cases would be Eigen vectors. We just copy the chunk (or maybe do something smart to wrap around that vector) into some SGVector and return that. we can do the "sum-then-divide" thing for native cases (see below)
- For Native backend, maybe it would be good to return floating point means for ints. I guess for int vectors, the best way to go is to compute running means, in order to avoid overflow. But that can be done later. It's not that tough to handle two different return-types using traits/auto+decltype. We can change it later when we feel like. But that's not a priority for now.

Also, do you thing that the API I proposed in [this post](https://github.com/shogun-toolbox/shogun/issues/3100) looks good enough? If we like this API, then maybe we can start porting the mean codes under this interface.

Great work by the way! Loving your code.

**Comment by OXPHOS** [comment]
Thank you and thanks for the comments : )  I got your point about piling up extra copies and I agree with you.
Sorry that I read the post a while ago and kinda forgot about it. If I understand it correctly, the API elaborates like:

```
linalg::elementwise(m).sum();

ElementwiseCalculation elementwise(SGMatrix/Eigen Matrix/GPU Matrix m) 
{
        return ElementwiseCalculation(m);
}

Class ElementwiseCalculation
{
        ElementwiseCalculation() { ... }        
        auto sum() { ... }
        auto product(SGMatrix/Eigen Matrix/GPU Matrix n) { ... }
}
```
But this easy implement leads to repeated creating-destroy of class instance for the same matrix `m`.

Alternatives are:
1) Save the most recent (last) instance and compare to the to-be-created one.
2) Functors? This can ensure only one instance per matrix `m`. However when `m` is destroyed, the functor sill exist and will pile up? This might be worse.

Also, I feel like I am actually implementing the NATIVE backend but not EIGEN3 now. Am I suppose to overload the `elementwise` method above like:

```
ElementwiseCalculation elementwise(SGMatrix m) 
ElementwiseCalculation elementwise(Eigen Matrix m)
ElementwiseCalculation elementwise(GPU Matrix m)
```
i.e. Pass on Eigen Matrix directly, but not the conversion from `SGMatrix` to `Eigen::Matrix` inside calculation methods we're using now?

**Comment by lambday** [comment]
Hi @OXPHOS, glad to hear your thoughts on this. Sorry for replying late.

Yes you're right, this class `ElementwiseCalculation` is exactly what I had in mind. However, before discussing that, I would like to just share my thoughts on a few things in general

- Our `linalg` API should only deal with Shogun matrix/vector types (`SG` and `CGPU`). It shouldn't take with `Eigen3` matrices. If someone is using `Eigen3` matrices directly inside his code, he can easily call `Eigen3` methods and therefore won't need to go through the `linalg` calls.
- The idea here is to remove the annoying `linalg::BACKEND::EIGEN3|VIENNACL` thing. So let's assume that whenever we have a `SGMatrix/SGVector`, we are using `Eigen3` backend, and whenever we have `CGPUMatrix/CGPUVector` we are gonna use `ViennaCL` backend. I think `NATIVE` implementation only makes sense for `custom(...)` operations that I mentioned in the post. So apart from that, we won't provide `NATIVE` implementations anymore. 
- The `linalg` API would then just consist of a bunch of overloaded methods, taking either `SG`/`CGPU` types. So, instead of going through those bunch of wrappers (in `modules`) and then internally calling `implementation::foobar::compute(...)` thing, we just reduce this down to one call. It's easy to write, easy to read, easy to execute.
- There should **never** be a hidden cost. No implicit type-conversions (we presently have this thing where we convert CPU matrix to GPU one, without letting the devs know the cost inside it) . CPU methods will work **only** with SG types, and GPU methods for CGPU types.

Now, about the ` ElementwiseCalculation` class, you're absolutely right. We want to avoid temporary object creation. So, what I had in mind is that we keep a static instance for each type, and return the same object every-time `elementwise(...)` is called, with just a reference to the underlying matrix/vector type set inside

Something like
```c++
template <class ContainerType>
ElementwiseCalculation<ContainerType>& elementwise(ContainerType& c)
{
    static ElementwiseCalculation<ContainerType> instance;
    return instance.with(c);
}

template <class ContainerType>
struct ElementwiseCalculation
{
    ElementwiseCalculation& with(ContainerType& c) { 
        container = c; // no deep copy, just increases refcount
    }
    // other methods you mentioned
    ContainerType container;
};
```
Pros:
- Doesn't create temporary object each time (a) per call, or even (b) per matrix (c). There is a fixed number of `ContainerType` instances (SGMatrix, SGVector, CGPUMatrix, CGPUVectors - with 8 primitive scalar types at max, typically only `float32_t` and `float64_t`).
- Does not create any duplicate copy of the data. The `with` method only increases refcount of the object.

Cons:
- The impl is doomed when being used in a multi-threaded application (two different threads calling `colwise(m).sum()` with different `m`. Have to protect it using some `mutex` stuff which is costly.
- The methods will keep a refcount of a matrix/vector of the last called method even if it is no longer being used anywhere else, preventing the memory to be freed. We need to either (1) manually remove the reference after each method call, or (2) create a non-refcounted wrapper around the passed matrix/vector.

So, now that I am thinking this through, it is messy.

Alternatives:

- We make the `ElementwiseCalculation` class stateless. The API then becomes
```c++
linalg::colwise().sum(m); 
linalg::elementwise().custom(m, /* my favorite lambda, go crazy */); 
```
The impl would be something like
```c++
const ColwiseCalculation& colwise()
{
    static const ColwiseCalculation instance;
    return instance;
}

struct ColwiseCalculation
{
    // bunch of overloaded methods
    template <typename ScalarType> auto sum(SGMatrix<ScalarType>& m) const { ... }
    template <typename ScalarType> auto sum(CGPUMatrix<ScalarType>& m) const { ... }
    // and so on
};
```

Pros: 
    - Just one instance of ColwiseCalculation of 1 byte, shogun-wise
    - Thread-safe

- Simply use namespace.
```c++
linalg::colwise::sum(m);
linalg::elementwise::custom(m, /* my favorite lambda, go crazy */); 

namespace colwise
{

// bunch of overloaded methods
template <typename ScalarType> auto sum(SGMatrix<ScalarType>& m) { ... }
template <typename ScalarType> auto sum(CGPUMatrix<ScalarType>& m) { ... }
// and so on

}
```
Pros: 
    - No overhead
    - Thread-safe

Looking at this list, I feel that maybe namespace is the way to go. Maybe @karlnapf can share his thoughts. Please feel free to share your thoughts and suggestions.

Also, it might be a good idea to come up with a concrete list of methods we should aim for. I think along with these basic sum/mean/custom operation, we should provide some block-based operations as well. Many of them are already there. It is more of a re-organizing task to make it actually useful.

We may like to port a few parts of an algorithm itself to linalg (suggestion by @lisitsyn) and I think it would be of some actual effect in Shogun. In that case, we can make use of our `custom` method if that is rock solid.

About cleaning up the mess in linalg that is there right now, I can help a bit with that. It's good that we discussed about this thing. Please let me know if you have any questions.

**Comment by OXPHOS** [comment]
Thanks for sharing the thoughts! I was enjoying the weekend and working on some other stuff. I will read and digest the words above ASAP.

**Comment by lambday** [comment]
Hi @OXPHOS, don't worry. It is just as important to blow off some steam, especially on the weekends :)

Good thing is, since this is the discussion phase, we don't have to jump to the implementation right away. It's better that we take time, think about pros and cons and finalize the exact tasks to be done in the coding phase :)

Also, I am discussing a few design decisions with others. Will let you know about that soon!

**Comment by OXPHOS** [comment]
@lambday I agree with you. Yes I saw your passionate discussions in the e-mail archive. Thanks for keeping me updated. So I'll slow down steps and do more research on C++ Primer.
