### ISSUE TITLE
Implement a nice progress bar

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3509]
We currently have SG_PROGRESS in Shogun.

This task is to:

 * implement progress in all main outer loops
 * think about multi-core cases
 * implement with interactive modular langauges, e.g. https://github.com/tqdm/tqdm

First figure out how SG_PROGRESS works, try to use it, and then go from there....
*All* methods in the docs should have a progress...

**Comment by geektoni** [comment]
@karlnapf 
About this one, would it be better a new implementation that will substitute SG_PROGRESS or an "upgrade" of SG_PROGRESS to make it also show a progress bar?

Btw, the current ```SGIO::progress``` implementation is faulty because in some cases it will display completely wrong timing information (I tried to use it with the cpp KNN meta example and the results were somewhat surprising ;) )

**Comment by karlnapf** [comment]
Steps:

1. Use SG_PROGRESS in cases where it is not used, i.e. all outer loops where it makes sense. This is more a task of identifying methods that dont have any progress at all (x-validation, grid-search, gradient model selection, etc)
2. Fix behaviour of SG_PROGRESS if wrong
3. If there are design short-comings in SG_PROGRESS, discuss/suggest an improvement. Investigate how other libs do this, check if we can adapt ideas. Potentially refactor all of SG_PROGRESS uses in Shogun

All steps are independent but I think this is a good order of approaching them

**Comment by karlnapf** [comment]
LeastAngleRegression needs one

**Comment by vigsterkr** [comment]
this is dooone :)
