### ISSUE TITLE
shogun installation error

### ISSUE THREAD

**Issue by palashahuja** [shogun-toolbox/shogun#3604]
I have tried installing shogun on ubuntu 16.04 but I am receiving the following error
usr/local/lib/libbz2.a(bzlib.o): relocation R_X86_64_32S against `BZ2_crc32Table

'The compiler shows to use the fPIC flag, so I tried adding the fPIC flag in the CMakeLists.txt,, CMakeCache.txt and the Makefile but it doesn't work please help

**Comment by besser82** [comment]
You are trying to link against a custom compiled static-archive of bzip2…  That's relly odd somehow…  Try to remove `usr/local/lib/libbz2.a` and install your system's `libbz2-dev`.  Then rebuild Shogun in a fresh build-tree and all should go fine.

Unfortunately I cannot assist you linking Shogun against a custom-built bzip2, since I do not know how it was compiled and all…

Please report, if your problem was solved

**Comment by palashahuja** [comment]
@besser82 That worked, thanks !
