### ISSUE TITLE
Refactor GP unit tests to use data fixtures

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#3947]
A lot of the GP unit tests are defining the same data in multiple test cases, resulting in huge code files with large redundant parts.

This task is to use the fixture concept to pull data generation to a class that the tests then extend.

There are some tests in Shogun that are doing this (right @vigsterkr ?). It is a nice task to get familiar with fixtures, googletest and Shogun in general

**Comment by Sahil333** [comment]
@vigsterkr can you give reference to those tests?

**Comment by karlnapf** [comment]
grep for GaussianProcess in `shogun/tests/unit`

**Comment by durovo** [comment]
Hello, I am trying to work on this issue as no one seems to have worked on it for quite some time.
I have identified these two files that have GP unit tests: 
classifier/GaussianProcessClassification_unittest.cc
regression/GaussianProcessRegression_unittest.cc
I also went through some other shogun unit tests where fixtures have been used such as FisherLDA_unittest.cc, BinaryLabels_unittest.cc, and RandomForest_unittest.cc. 

In the file GaussianProcessClassification_unittest.cc test cases GaussianProcessClassificationUsingSingleLaplaceWithLBFGS, GaussianProcessClassificationUsingKLCovariance, GaussianProcessClassificationUsingKLCholesky, etc. define and use the same data. Since the test case names are different in these, they cannot use the same test fixture class. Would it be fine to create a base fixture class and create several other classes with appropriate names for each test case that inherit from this base class?

**Comment by karlnapf** [comment]
Hi @durovo and welcome! Great that you want to work on this

That would be ok. In fact, anything that reduces the bloated code.

 * a class that generates the data shared by all these tests
 * a class that sets up the GP pipeline that is used in many of the tests (e.g. one for each of the inference methods, one for regression/classification, etc, .... anything that is set up more than twice should be grouped this way

Let me know if you have any questions

**Comment by durovo** [comment]
Hello @karlnapf ,  I have refactored GaussianProcessClassification_unittest.cc. However in GaussianProcessRegression_unittest.cc, the same data is almost never used more than twice in the nine tests. Also, since we can have only one fixture class for each TestName, I cannot think of any good way of refactoring it.

**Comment by karlnapf** [comment]
Closed in #3990
