### ISSUE TITLE
cannot kill a running task

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4201]
try any long running python example and try to ctrl-c.... only `kill -9 <PID>` works.

**Comment by geektoni** [comment]
I think this may be caused by the premature stopping feature. I believe this line https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/base/init.cpp#L101 is causing the problem you are running into. I'll have a closer look later today.

**Comment by vigsterkr** [comment]
@geektoni so i'm guessing the reason it is currently not doing anything is because of this:
https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/Signal.cpp#L17

since in the handler:
https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/Signal.cpp#L36

do you know why it is by default turned off? :)

**Comment by geektoni** [comment]
I think we wanted to let the user decide what behaviour Ctrl+C to use. In fact, here https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/Signal.h#L76 there is the method to enable the custom signal handler.

Anyway, this line https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/Signal.cpp#L37 is clearly wrong, it should have an exit call instead of return. I'll provide a patch to fix that. Shall I also change the behaviour of the signal handler to be always active?

**Comment by vigsterkr** [comment]
@geektoni i would rather have it by default active as currently if you run a model and wanna cancel it the only way to do is to kill the process :) which is not the most user friendly behaviour :P
