### ISSUE TITLE
With Octave on Ubuntu 16.04: Stuck in installation at cmake

### ISSUE THREAD

**Issue by carbonox-infernox** [shogun-toolbox/shogun#4396]
I am following the instructions here: http://www.shogun-toolbox.org/install#manual-basics

When i do `cmake .. -DINTERFACE_OCTAVE=ON`

I get the error
`CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Octave (missing: OCTAVE_ROOT_DIR) (found suitable version
  "4.4.1", minimum required is "3.6")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOctave.cmake:189 (find_package_handle_standard_args)
  src/interfaces/octave/CMakeLists.txt:1 (FIND_PACKAGE)`

**Comment by lisitsyn** [comment]
I checked this thing and the reason is that `OCTAVE_ROOT_DIR` is detected via `octave-config -p PREFIX` which is not supported anymore. I didn't find any mentions of that in CHANGELOG of Octave but I guess we should adapt `FindOctave`. Luckily, this directory seems to be unused. This means deleting it from the argument list of `find_package_handle_standard_args` should help.
