### ISSUE TITLE
For loop for examples meta-language 

### ISSUE THREAD

**Issue by avramidis** [shogun-toolbox/shogun#4418]
I am in the process of converting the shogun/examples/undocumented/python/distribution_hmm.py to a meta example. I am stuck at the lines with the for loops.

I checked the meta language files and could not find any mechanism for loops. I am happy to implement it if that is the case.

Thanks!

**Comment by karlnapf** [comment]
Hi!

Thanks for getting involved here.
There currently is neither a LOOP or a WHILE construct in the meta language... the language is supposed to be very simple and only just expressive enough for API examples.

We might change this at some point, but it is unlikely for now. What we usually do is to load datasets from files in case you want to generate training data. Have a look at the other examples to find inspiration.

Let me know if you need further help. This issue is best discussed on the mailing list, irc, or on stackoverflow.
