### ISSUE TITLE
Unable to build shogun's python interface

### ISSUE THREAD

**Issue by braceletboy** [shogun-toolbox/shogun#4578]
Hi, I have been trying to build shogun's python interface from source code. But, I always get the following error message (I have turned on verbose for the make command. Hence the lengthy messages):
```
[ 74%] Built target python_doxy2swig
make -f src/interfaces/python/CMakeFiles/interface_python_src.dir/build.make src/interfaces/python/CMakeFiles/interface_python_src.dir/depend
make[2]: Entering directory '/media/Rukman/IIT_B/gumption/shogun/build_python'
cd /media/Rukman/IIT_B/gumption/shogun/build_python && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /media/Rukman/IIT_B/gumption/shogun /media/Rukman/IIT_B/gumption/shogun/src/interfaces/python /media/Rukman/IIT_B/gumption/shogun/build_python /media/Rukman/IIT_B/gumption/shogun/build_python/src/interfaces/python /media/Rukman/IIT_B/gumption/shogun/build_python/src/interfaces/python/CMakeFiles/interface_python_src.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/media/Rukman/IIT_B/gumption/shogun/build_python'
make -f src/interfaces/python/CMakeFiles/interface_python_src.dir/build.make src/interfaces/python/CMakeFiles/interface_python_src.dir/build
make[2]: Entering directory '/media/Rukman/IIT_B/gumption/shogun/build_python'
[ 74%] copying SWIG files
make[2]: Leaving directory '/media/Rukman/IIT_B/gumption/shogun/build_python'
[ 74%] Built target interface_python_src
make -f src/interfaces/python/CMakeFiles/_interface_python.dir/build.make src/interfaces/python/CMakeFiles/_interface_python.dir/depend
make[2]: Entering directory '/media/Rukman/IIT_B/gumption/shogun/build_python'
[ 75%] Swig source
cd /media/Rukman/IIT_B/gumption/shogun/build_python/src/interfaces/python && /usr/bin/cmake -E make_directory /media/Rukman/IIT_B/gumption/shogun/build_python/src/interfaces/python
cd /media/Rukman/IIT_B/gumption/shogun/build_python/src/interfaces/python && /usr/bin/swig3.0  -python -builtin -modern -modernargs -threads -w473 -w454 -w312 -w325 -fvirtual -outdir /media/Rukman/IIT_B/gumption/shogun/build_python/src/interfaces/python -c++ -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/media/Rukman/IIT_B/gumption/shogun/src -I/media/Rukman/IIT_B/gumption/shogun/build_python/src -I -I/media/Rukman/IIT_B/gumption/shogun/src/gpl -I/media/Rukman/IIT_B/gumption/shogun/build_python/StanMath/src/StanMath -I -I/media/Rukman/IIT_B/gumption/shogun/build_python/StanMath/src/StanMath/lib/boost_1.66.0 -I -I/media/Rukman/IIT_B/gumption/shogun/build_python/StanMath/src/StanMath/lib/sundials_3.1.0/include -I -I/media/Rukman/IIT_B/gumption/shogun/build_python/StanMath/src/StanMath/lib/eigen_3.3.3 -I -I/media/Rukman/IIT_B/gumption/shogun/build_python/src/shogun/third_party -I -I/media/Rukman/IIT_B/gumption/shogun/build_python/src/shogun/third_party/variant -I -I/usr/include -I/usr/include/json-c -I/usr/include/libxml2 -I/usr/include/hdf5/serial -o /media/Rukman/IIT_B/gumption/shogun/build_python/src/interfaces/python/shogunPYTHON_wrap.cxx /media/Rukman/IIT_B/gumption/shogun/build_python/src/interfaces/python/shogun.i
shogun_doxygen.i:612: Error: Syntax error in input(1).
src/interfaces/python/CMakeFiles/_interface_python.dir/build.make:64: recipe for target 'src/interfaces/python/shogunPYTHON_wrap.cxx' failed
make[2]: *** [src/interfaces/python/shogunPYTHON_wrap.cxx] Error 1
make[2]: Leaving directory '/media/Rukman/IIT_B/gumption/shogun/build_python'
CMakeFiles/Makefile2:475: recipe for target 'src/interfaces/python/CMakeFiles/_interface_python.dir/all' failed
make[1]: *** [src/interfaces/python/CMakeFiles/_interface_python.dir/all] Error 2
make[1]: Leaving directory '/media/Rukman/IIT_B/gumption/shogun/build_python'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2
```
I have looked at the 612 line of the `shogun_doxygen.i` file but I am not sure I understand the error generated. I am also posting the [shogun_doxygen.i][1] file as a gist.

Thanks in advance for the help :)

[1]: https://gist.github.com/braceletboy/c2685d8c5bb768a4544d172e9199ab5f

**Comment by gf712** [comment]
Hi, are you using the latest develop? This issue should have been fixed a few commits ago..

**Comment by braceletboy** [comment]
I was not. Thank you. Will rebase to the newest commit and try again.

**Comment by braceletboy** [comment]
Thanks alot @gf712 . I am closing this issue.

**Comment by VisintZJ** [comment]
Hey, I met the same error when I run 'make' after 'cmake'. How did you solve it?

**Comment by gf712** [comment]
Hi, doxygen doesn't seem to support all modern c++ syntax and we don't test it in the CI.. so maybe at some point someone introduced a "bug" after this issue was fixed.
You could disable doxygen. I'll have a look into it.

**Comment by VisintZJ** [comment]
Thanks a lot @gf712 ! I will have a try.

**Comment by VisintZJ** [comment]
By the way, how can I disable doxygen? @gf712 I uninstall doxygen and 'cmake' command said it need doxygen.

**Comment by gf712** [comment]
If you uninstalled it now you need to remove CMakeCache.txt in the build folder and run cmake again. Then cmake should run fine!

**Comment by VisintZJ** [comment]
@gf712 Thanks! This problem was solved. But I met a new error when I run 'make' command, here is the error message about new problem:

[ 91%] Built target cpp-kernel-auc
[ 91%] Linking CXX executable distance/cpp-distance-manhattan
[ 91%] Built target cpp-distance-manhattan
[ 91%] Linking CXX executable kernel/cpp-kernel-anova
[ 91%] Built target cpp-kernel-anova
[ 91%] Linking CXX executable kernel/cpp-kernel-chi2
[ 91%] Built target cpp-kernel-chi2
[ 91%] Linking CXX executable kernel/cpp-kernel-log
[ 91%] Built target cpp-kernel-log
[ 91%] Linking CXX executable neural_nets/cpp-neural_nets-feedforward_net_classification
[ 91%] Built target cpp-neural_nets-feedforward_net_classification
[ 91%] Linking CXX executable evaluation/cpp-evaluation-cross_validation
[ 91%] Built target cpp-evaluation-cross_validation
[ 91%] Linking CXX executable meta_api/cpp-meta_api-calls
[ 91%] Built target cpp-meta_api-calls
[ 91%] Building CXX object examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/meta_api/literals.cpp.o
/home/zhangjing/packages/shogun/build/UILD_META_EXAMPLES=ON/examples/meta/cpp/meta_api/literals.cpp:5:25: error: ‘io’ is not a namespace-name
 using namespace shogun::io;
                         ^~
/home/zhangjing/packages/shogun/build/UILD_META_EXAMPLES=ON/examples/meta/cpp/meta_api/literals.cpp:5:27: error: expected namespace-name before ‘;’ token
 using namespace shogun::io;
                           ^
examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/build.make:62: recipe for target 'examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/meta_api/literals.cpp.o' failed
make[2]: *** [examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/meta_api/literals.cpp.o] Error 1
CMakeFiles/Makefile2:5592: recipe for target 'examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/all' failed
make[1]: *** [examples/meta/cpp/CMakeFiles/cpp-meta_api-literals.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

Do you have any idea about this question? I'm sorry to disturb you again but I have no idea about this.

**Comment by vigsterkr** [comment]
@VisintZJ unfortunately this is "known" as in that specific meta example cpp no headers are included that contains the `shogun::io` namespace, hence the error. The are several ways to fix this in your case the easiest temporary solution is that simply remove the specific line from `examples/meta/cpp/meta_api/literals.cpp` and do a make again

**Comment by vigsterkr** [comment]
@VisintZJ for the `literals.cpp` i've created a separate bug #4770

**Comment by VisintZJ** [comment]
@vigsterkr Thank you very much! The problem has been solved after I remove that line and I have ‘make’ successfully. Thanks for your patient answers！ @gf712
