### ISSUE TITLE
put() with custom constraints.

### ISSUE THREAD

**Issue by geektoni** [shogun-toolbox/shogun#4638]
When I remove getters/setters in favour of the new `get()`/`put()` utilities, it happens to me to find these kinds of methods:
```c++
void CKMeansBase::set_k(int32_t p_k)
{
	REQUIRE(p_k>0, "number of clusters should be > 0");
	this->k=p_k;
}
```
This setter can be removed easily, the only issue is caused by the `REQUIRE`. As far as I know, the `put()` mechanism does not allow to specify those kinds on preconditions on the input. 

I was wondering if it could make sense to extend the `get()`/`put()` framework to allow also to specify these kinds of constraints when registering a parameter, like:
```c++
SG_ADD(&k, "k", "k, the number of clusters", REQUIRE(k>0, "number of clusters should be > 0"),  ParameterProperties::HYPER);
```

**Comment by karlnapf** [comment]
Yes, very good points.

As of now, we have moved these kind of checks into the `train` method, or similar. So that everything is checked before committing to computation. So when you remove setters with those checks, pls move the checks to appropriate places.

A better way to do this would be to add domain checks as some kind of property of the variable. @vigsterkr and me had discussed this many times, but without coming up with some kind of concept for it. One straight forward way would be to use the properties we have, like `ParameterProperties::READONLY`, which is checked in all the `put` calls. Similar there could be a `POSITIVE` property. However, this might scale badly in the sense that if we add more and more properties that involve checks, there is more and more overhead when calling put.

**Comment by lisitsyn** [comment]
I think AnyParameter should have a list of requirements/constraints and once we declare the variable we also add the constraints in a builder-like syntax.

**Comment by gf712** [comment]
This has already been implemented
