### ISSUE TITLE
Can CMake switch -DENABLE_TESTING=ON be set by default?

### ISSUE THREAD

**Issue by kurtamohler** [shogun-toolbox/shogun#4762]
Hey there, I was following the instructions in DEVELOPING.md because I want to make a contribution. When I got to the "Testing" step, I saw that I had to enable the -DENABLE_TESTING=ON CMake switch. So I did that, but then I had to rebuild everything, because changing a cmake flag requires a rebuild.

On my machine, shogun takes more than an hour to build. (I know about "make -j <number>", which would normally speed things up. But for some reason using -j for this project seizes up my computer, making it unresponsive, even if I only use "-j 2".) So it was really annoying to have to build it twice.

Is there a good reason why -DENABLE_TESTING=ON isn't set by default? Is anyone opposed to changing it? I'd be happy to submit a PR. If we can't have it on by default, I think it would at least be nice to mention in INSTALL.md that contributors need to enable this flag before they run make--that way no one has to build it twice.

**Comment by gf712** [comment]
Hi!

> On my machine, shogun takes more than an hour to build. (I know about "make -j ", which would normally speed things up. But for some reason using -j for this project seizes up my computer, making it unresponsive, even if I only use "-j 2".) So it was really annoying to have to build it twice.

You should install ccache if you want to develop shogun (or any other project) and need to recompile several times. This will speed up the process massively. The reason your computer froze is probably when compiling the linalg operations.. I am surprised -j 2 still caused issues though.

> Is there a good reason why -DENABLE_TESTING=ON isn't set by default? Is anyone opposed to changing it? I'd be happy to submit a PR. If we can't have it on by default, I think it would at least be nice to mention in INSTALL.md that contributors need to enable this flag before they run make--that way no one has to build it twice.

I think the reason is just that most people do not need to run the tests for the whole code base and they take a while to compile. Most just want to use it for research/production and just look at the CI to see if the code is working fine.

**Comment by vigsterkr** [comment]
second what @gf712 just wrote. plz use cchace, that'll speed up a lot your compilation time (after the first compile)

**Comment by karlnapf** [comment]
Compiling in debug mode also makes things much faster
