### ISSUE TITLE
DenseSubSamplesFeatures to DenseFeatures conversion

### ISSUE THREAD

**Issue by lejeunel** [shogun-toolbox/shogun#4795]
While training a random forest, I generate a DenseSubSamplesFeatures<double> from a DenseFeatures<double>.
Compilation works.
At runtime, I get:
```
RuntimeError: Object of type DenseSubSamplesFeatures cannot be converted to type shogun::DenseFeatures<double>.
```

I'm working on commit 84175ba7c8c73dd4028f217daf7a5f4c25c2adaf.
I compile with g++ 9.1.0 on Arch Linux.

Here's the code that generates the DenseSubSamplesFeatures
https://github.com/lejeunel/glia/blob/itk-5.0.1/src/shogun_helpers.hxx#L83

**Comment by vigsterkr** [comment]
this issue here is this:
https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/multiclass/tree/CARTree.cpp#L112

most of that code could be ported to use DotIterator so basically then having any DotFeatures (like DenseSubSamplesFeatures) could be passed... the only problem is this
https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/machine/RandomForest.cpp#L180

as it actually works on the matrix itself:
https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/multiclass/tree/CARTree.cpp#L297

**Comment by karlnapf** [comment]
A simple workaround would be to manually do the subset into a matrix and then pass that to dense features.....Good issue for ongoing GSoC students to add this.

**Comment by souvik3333** [comment]
Hi, Can I work on this?

**Comment by vigsterkr** [comment]
@souvik3333 of course, just send in a PR and we'll take it from there

**Comment by naruarjun** [comment]
Does this issue still need to be worked on? Or has it been resolved?
