### ISSUE TITLE
RandomFourierDotFeatures removal

### ISSUE THREAD

**Issue by jonpsy** [shogun-toolbox/shogun#4972]
I noticed we have two implementation of RandomFouierFeatures, 
1. ```src/shogun/features/RandomFourierDotFeatures``` 
2. ```src/shogun/preprocessor/RandomFourierGaussPreproc```

In my opinion RandomFourierDotFeatures should be removed because of the following reasons

1. In the python interface they're "exposed", and hence we can do
```
from shogun import RandomFourierDotFeatures
```
this is in contradiction to our strategy of only using the base factories as per issue #4463. 
2. As of what I gather, DotFeatures are an abstract class, but RandomFourierDotFeatures input args demand it in ```DotFeatures``` type. Trying to give ```<DenseFeatures>```  as input to arg throws type error.
```
RandomFourierDotFeatures(std::shared_ptr<DotFeatures> features, .... )
````
3. We generally handle data with DenseFeatures which is well handled by our RandomFourierGaussPreproc.
4. RandomFourierGaussPreproc has meta_example and it's ported in interfaces like python.

Seeing this in view, i think we should remove RandomFourierDotFeatures.

**Comment by karlnapf** [comment]
No, they serve different purposes, one is for on-the-fly, one is for batched projection. This is useful. The design is not the best (see my email to the mailing list on what can be improved).

You could start adding the on the fly features to the new public API, something like a new factory, `rff_feats = rff_features(features('my_csv'), kernel=my_k)`, and then make a meta example where this is passed to an svm. 

You are right about the type interface not being ready for the new API, so that needs some updates

**Comment by karlnapf** [comment]
I am closing this as we won't delete stuff
