### ISSUE TITLE
(IPython) notebook log

### ISSUE THREAD

**Issue by gf712** [shogun-toolbox/shogun#4975]
Currently I cannot see the log from the function calls when running code in the notebooks. The output is redirected to the `stdout` of the terminal. This can be convenient when there's a lot of logging happening, but a new user might be surprised when nothing is displayed when an algorithm is running.

It should be possible to redirect the stdout to notebook somehow. @theartful do you have any suggestions?

**Comment by ghost** [comment]
This is strange, `spdlog` didn't change output stream. Both before and after introducing `spdlog` the output was directed to `stdout`. This might be because of asynchronicity (logging in different thread)?
I will investigate.

**Comment by gf712** [comment]
I am not sure.. It might have been the case before with `std::cout`? But I saw that there is an option to choose the sink, so it would be good to figure out how to set it to the notebook?

**Comment by ghost** [comment]
Before we used `fprintf` with a FILE which was defaulted to stdout as well. So it's equivalent to `std::cout`.
https://github.com/shogun-toolbox/shogun/blob/ab274e7ab6bf24dd598c1daf1e626cb686d6e1cc/src/shogun/io/SGIO.cpp#L55-L60

**Comment by ghost** [comment]
I reproduced the problem locally. It seems to be a common issue with python and c/c++ libraries, and it becomes obvious when Jupyter is used. Jupyter listens for python's `sys.stdout/sys.stderr` but C and C++ bypasses them to write to the file descriptor directly. This blogpost explains it well https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/
I will write a patch and send it.

**Comment by ghost** [comment]
Also I misunderstood your last comment :"D It seems that it is the case before with `std:cout`.

**Comment by ghost** [comment]
I see two solutions:
1. Either we tamper with python's `sys.stdout` and file descriptors as is done here: https://github.com/minrk/wurlitzer As a consequence, we might need to decorate each function exposed from shogun, or otherwise these file descriptor changes will be global to the python session.
2. Or we change spdlog's sink as you suggested and somehow add a hook from that sink to python's `sys.stdout`. The problem here is with multithreading. I'm not sure how python will react to that.
I prefer your suggestion, I will see how it can be done.

Edit: I just noticed that `wurlitzer` can be used in Jupyter by adding the simple line `%load_ext wurlitzer`. So we can also use that, or instruct shogun users to use it.

**Comment by gf712** [comment]
@theartful thanks for looking into it so quickly! Just tested out `%load_ext wurlitzer` and it does exactly what I expected. Should write about this somewhere in the wiki. @vigsterkr this should probably also help displaying when using `xeus-cling`
