### ISSUE TITLE
Refactoring RandomFourierGaussPreproc

### ISSUE THREAD

**Issue by jonpsy** [shogun-toolbox/shogun#5009]
Currently, our implementation of RandomFourierGaussPreproc(RFGP) seems to be very outdated. @karlnapf  recommended some changes to it, in this issue I'm only highlighting how I plan to shorten the LoC and possibly improve the design so that it can be critiqued here itself. The draft is to be posted soon.

**Current map:**
The current architecture supports two ways to get random_coefficients.

1. You have generated the rand_coefficients, now want to apply to another RFF so you just pass the attributes(internal members) from previous to the newer use ```set_randomcoefficients()```
2. You start from scratch, 
a) Use the appropriate setters
b) Use init_randomcoefficients()

It depends on creating two separate variables for the same attribute (e.g. cur_dim_feature_space and dim_feature_space) where 
*  ```dim_feature_space``` is the desired value from the setter 
*  ```cur_dim_feature_space``` is set from the init_randomcoeff 

the ```test_rfinited()``` checks if there is a mismatch between the above values which would indicate that there is a need to recalculate random_weights & random_offset. This helps in saving computation.

**Proposed:**
My goal is to achieve the same end result but with lesser variables and shorter code. I'm trying this by using a boolean ```is_updated``` which defaults to false, changes if any of the following change
1. ``` kernelwidth```
2. ```dim_featurespace```
3. During ```fit()```  if the ```num_features``` of the input feature is different from ```get_dim_input_space()```

**Remove** dim_input_space, set_dim_input_space(), all "cur_" variables, test_rfinited()

**How it works**

- In the setters of attributes, use is_updated to see if it modifies the variable e.g.
```
set_kernel_width(int32_t kernel_width)
{
....
 is_updated =  this->kernel_width == kernel_width; 
}

set_feature_dim_space(int32_t dim)
{
...
is_updated = dim_feature_dim_space === dim;
}
```
In init and set coefficients the value is set to true at the end of process
```
init_randomcoefficients()
{
.....
is_updated = true;
}

set_randomcoefficients{ 
is_updated = true;
}
```
- since dim_input_space is removed, get_dim_input_space() returns ```random_weights.num_cols```
- In fit() function, based on is_updated it recomputes randomcoefficients
```
fit(Features f){
num_feats = f->num_features;
is_updated = get_dim_input_space() == num_feats ; //Check if num_feats is newer or the old

if(!is_updated){
     // Handle null values of attributes
     init_random_coefficients(num_feats)
}
else{
SG_DEBUG("Already instantiated !, keeping old values");
}
```

**Comment by karlnapf** [comment]
Good initiative. Though I also don't understand some of the ideas in the snippets. Let's discuss this in PRs, not issues. 

BTW here is what I suggested in an email on the list. There are much more immediate things you can to do modernise the code, see the examples below

* using linalg instead of loops
* pulling shared code out instead of having the same operations twice
* have illustrations (notebooks, examples) for the different use cases (say SVM vs KRR)
* make the design modular, so that different kernels are supported without having to write new classes (e.g. add the spectral density of the kernels somewhere and the framework simply samples from that
* clean up the class docs
* rename methods, shorten class names
* look at the API of sklearn to see what we can learn
* add the fast-food method (which is a faster way for computing the RFF in high input dimensions)

And then clean up the existing RFF code. Examples looking at the RandomFourierGaussPreproc.cpp:
* remove SG_MALLOC, refactor using SGVector/SGMatrix
* improve the error messages
* merge cur_kernelwidth and kernelwidth, and same for the other vars
* remove "dim_input_space" which shouldnt be needed
* remove test_rfinited, which is really bad design
* dont define PI locally, use the one in C++
* use our gaussian rng rather than doing the gauss transform from uniform numbers (lines 246ff)
* performance improve: don't apply the embedding vector wise when receiving a matrix. Mat-Mat products are faster!
