### ISSUE TITLE
Julia interface

### ISSUE THREAD

**Issue by azev77** [shogun-toolbox/shogun#5073]
Hi and thank you for this package. 
Is there any chance you will consider implementing a Julia interface? 
We'd love to have access to your stuff!

**Comment by gf712** [comment]
Hi, it’s something we want to implement at some point, but there is no timeline. We are working towards a factory pattern API, which makes it much easier to expose shogun to other languages. But until that is complete we will probably not have great support for Julia. If you’re interested have a look at shogun-rust. We would probably use a similar approach.

**Comment by karlnapf** [comment]
We tried to connect with the Julia community a few times, propose a joint effort in building a swig backend for julia. But we didn't meet that much interest, presumably because the shogun API is not really julia-nic. It also was a few years back and things might have changed since then.

These days probably the approach that @gf712 mentioned above would be preferred over another swig binding ... but manpower is the issue here. If you know someone who is interested in contributing to this, send them in our direction :)

**Comment by karlnapf** [comment]
PS I guess you know that MLPack has a julia interface?
