### ISSUE TITLE
OpenMP probably does not work with C++11 features (including std::shared_ptr)

### ISSUE THREAD

**Issue by ghost** [shogun-toolbox/shogun#5121]
The example `cross_validation_support_vector_machine` fails with high probability (double free / segfault).
Running valgrind showed that the source of the problem is the function `evaluate_one_run` in CrossValidation. I reported this bug before, suspecting that the problem is `SG_REF` and `SG_UNREF`.
It turns out that openmp does not officially support C++11 features including `std::atomic` and `std::shared_ptr`. Some implementations support them unofficially, but it seems that mine doesn't.
Removing the line for using openmp fixes the problem.

Resources:
https://stackoverflow.com/questions/21554099/can-stdatomic-be-safely-used-with-openmp
https://stackoverflow.com/questions/53198251/openmp-and-shared-ptr

**Comment by vigsterkr** [comment]
thnx a lot for looking into this :( it's quite a sad news.... what's the compiler you've testing?

**Comment by theartful** [comment]
I'm using gcc version 9.3.0

**Comment by theartful** [comment]
Running valgrind on many of the examples reports "possibly lost" memory leaks. One of sources is OpenMP. For example DotFeatures::dot. I really don't get how this is the case, since openmp must use threading primitives, and shared_ptr control block is thread safe.

**Comment by gf712** [comment]
OpenMP also has a lot of false positives in valgrind. That is because memory management is handled by the openmp runtime, which probably has some static initialisation of thread pools and valgrind cannot track all mem allocs/free. I think it is safe to assume that most the warnings related to openmp can be ignored. I think some projects add these OpenMP related warnings to the valgrid suppression file.

**Comment by vigsterkr** [comment]
we do have our suspension file: https://github.com/shogun-toolbox/shogun/blob/develop/configs/valgrind.supp

hasn't been updated in a while though
