### ISSUE TITLE
Installation issue with Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by imsiddhant07** [shogun-toolbox/shogun#5135]
I tried installing the shogun ml package on Ubuntu, was following the steps instructed on [install.md](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INSTALL.md) and on the [website](https://www.shogun-toolbox.org/install#ubuntu).
I wanted to install and start working on the codebase, thought I could contribute. But it won't go past the installation step.
It says Shogun does not have a stable release for Ubuntu focal (i.e 20.04 LTS) I'll add a [screenshot](https://drive.google.com/file/d/1xoZdE6BuwIkRf4cAppVwjc6mALIl9tlt/view?usp=sharing) for assistance.

**Comment by gf712** [comment]
Hi, there's currently no release for Ubuntu focal. You could either install shogun with anaconda (I think you can install the last release that way) or compile from source.

**Comment by siddhantjain07** [comment]
Hello @gf712, I tried building it from the [source](https://github.com/shogun-toolbox/docs/blob/master/INSTALL.md#manual) using the commands as it is
The `cmake ../` does not build the, stops with errors.
Then I tried building it from the repository itself but again cmake seems to have some issue.

Also, does shogun have any community forum for interaction with peers I tried communicating on IRC channel but it seems to be inactive?

**Comment by gf712** [comment]
You'll have to see what the error is that cmake is returning. You are likely missing some dependency. The IRC channel is a bit quiet at the moment because all the devs (including myself) are busy with other projects and jobs. If you cannot resolve your issue feel free to open an issue/explain your problem here and someone will have a look and help :)

**Comment by pandeyanuradha** [comment]
Hey, @gf712 @siddhantjain07 , could you find a workaround for that?
I was able to download it via anaconda, but am still not able to compile it from source, am not able to compile _make_.

**Comment by siddhantjain07** [comment]
Hey @pandeyanuradha,
maybe you could try installing the dependencies that are pointed out when the cmake or make fails.

**Comment by pandeyanuradha** [comment]
Thanks for the quick reply. 
@siddhantjain07 were you able to resolve it that way? I am still getting cmake errors. Also, I have installed shogun through anaconda, so is that enough?

**Comment by pandeyanuradha** [comment]
Hi @gf712,
This is the error that I am getting.
 `-- verifying file...
       file='/home/ubuntu/shogun/third_party/Eigen3/3.3.4.tar.bz2'
-- MD5 hash of
    /home/ubuntu/shogun/third_party/Eigen3/3.3.4.tar.bz2
  does not match expected value
    expected: 'a7aab9f758249b86c93221ad417fbe18'
      actual: 'd41d8cd98f00b204e9800998ecf8427e'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/home/ubuntu/shogun/third_party/Eigen3/3.3.4.tar.bz2'
   timeout='none'
-- Using src='https://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2'
`
Then it tries to connect with : https://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2, but this website doesn't exist. 
And then, in the end,
`make[2]: *** [src/shogun/CMakeFiles/Eigen3.dir/build.make:91: Eigen3/src/Eigen3-stamp/Eigen3-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:750: s`

Any workaround for this?

**Comment by gf712** [comment]
Hmm I thought I had fixed that error. Is that using the latest commit from the develop branch?

**Comment by pandeyanuradha** [comment]
@gf712 Yes. Is this some problem with the version of eigen?

**Comment by pandeyanuradha** [comment]
Hi @gf712 ,
I managed to compile shogun, and run the make command. Now, while running the make/ make install command, this is the error that I am getting:
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.8.6")
CMake Warning at CMakeLists.txt:411 (MESSAGE):
  Doxygen based documentation generation is enabled, but couldn't find
  doxygen.

  In order to turn off this warning either disable doxygen documentation
  generation with -DENABLE_DOXYGEN=OFF cmake option or install doxygen.


-- dir='/home/ubuntu/shogun/src'
-- dir='/home/ubuntu/shogun/build/src'
-- dir='/home/ubuntu/shogun/src/gpl'
-- Using system's malloc
-- Could NOT find ViennaCL (missing: VIENNACL_INCLUDE_DIR VIENNACL_ENCODED_VERSION) (Required is at least version "1.5.0")
-- Could NOT find rxcpp (missing: rxcpp_INCLUDE_DIR) 
-- Could NOT find TFLogger (missing: TFLogger_DIR)
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- LAPACK requires BLAS
-- Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find LibArchive (missing: LibArchive_LIBRARY LibArchive_INCLUDE_DIR) 
-- Could NOT find CPLEX (missing: CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find MOSEK (missing: MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY MOSEK_LIBRARIES) 
-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
-- Unable to determine HDF5 C flags from HDF5 wrapper.
-- Unable to determine HDF5 C version from HDF5 wrapper.
-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found version "")
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Could NOT find LibLZMA (missing: LIBLZMA_LIBRARY LIBLZMA_INCLUDE_DIR LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Could NOT find SNAPPY (missing: SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Lzo includes and libraries NOT found. 
-- Could NOT find NLOPT (missing: NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing: LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing: COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find ARPREC (missing: ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Linker: GNU gold
CMake Warning (dev) at src/interfaces/python/CMakeLists.txt:3 (FIND_PACKAGE):
  Ignoring EXACT since no version is requested.
This warning is for project developers.  Use -Wno-dev to suppress it.

**CMake Error at cmake/FindNumPy.cmake:62 (message):
  NumPy import failure:**

Call Stack (most recent call first):
  src/interfaces/python/CMakeLists.txt:4 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/shogun/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/shogun/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:3860: cmake_check_build_system] Error 1

Out of which, I believe, only the bold lines are problematic. I am able to import NumPy perfectly fine, but there's still this error. I tried googling it, but with no success. Can you please help me?

**Comment by UmarJ** [comment]
@pandeyanuradha If you need python interfaces, you need the `python-dev python-numpy` packages on Debian/Ubuntu.

**Comment by pandeyanuradha** [comment]
Hey @UmarJ , there was a problem with the anaconda environment that I was using, and I was able to fix that issue. But now when I am trying to compile the .py files, this is the error that I am getting:
`AttributeError: module 'shogun' has no attribute 'read_csv'`
Any idea what's wrong?

**Comment by UmarJ** [comment]
@pandeyanuradha No idea, I only built the C++ interface.

**Comment by deto** [comment]
@pandeyanuradha how did you get it to build?  I'm running into the same issue with the file from eigen bitbucket not existing.

**Comment by pandeyanuradha** [comment]
@deto Nope, I couldn't fix it. Unfortunately, this thread became very inactive. You can try degrading your version of Ubuntu from 20.04 to 18.04, that seems like the only feasible option to me.

**Comment by deto** [comment]
I don't know how the Ubuntu version would fix this, though, as the file that the build script tries to download just doesn't exist at that bitbucket location anymore.

I ended up using a conda environment to get it to build.  Had to make a separate environment as there are only conda packages for python 3.6 or lower but then it worked fine.
